"""Catalog SIMPLE: контент Product и исправленный Default, без JSON/JSONB."""

from uuid import UUID
from datetime import UTC, datetime
from alembic import op
import sqlalchemy as sa

revision = "0017_catalog_simple"
down_revision = "0016_remove_inventory"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Создаёт tenant-таблицы и Default: PRODUCT из трёх блоков, VARIANT из двух."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_content_block_definitions",
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value_type IN ('text','rich_text')", name="ck_catalog_block_value_type"
        ),
        sa.CheckConstraint("revision>0", name="ck_content_block_revision"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "catalog_product_types",
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("revision>0", name="ck_product_type_revision"),
        sa.CheckConstraint("schema_version>0", name="ck_catalog_type_version"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "catalog_content_block_translations",
        sa.Column("content_block_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "char_length(btrim(label)) BETWEEN 1 AND 255",
            name="ck_content_block_translation_label",
        ),
        sa.ForeignKeyConstraint(
            ["content_block_id"],
            ["catalog_content_block_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_block_id", "locale"),
    )
    op.create_table(
        "catalog_product_type_content_blocks",
        sa.Column("product_type_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "scope IN ('PRODUCT','VARIANT')", name="ck_catalog_link_scope"
        ),
        sa.CheckConstraint("position>=0", name="ck_catalog_link_position"),
        sa.ForeignKeyConstraint(
            ["block_id"], ["catalog_content_block_definitions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"], ["catalog_product_types.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("product_type_id", "block_id", "scope"),
        sa.UniqueConstraint(
            "product_type_id", "scope", "position", name="uq_catalog_link_position"
        ),
    )
    op.create_table(
        "catalog_product_type_translations",
        sa.Column("product_type_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "char_length(btrim(label)) BETWEEN 1 AND 255",
            name="ck_product_type_translation_label",
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"], ["catalog_product_types.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("product_type_id", "locale"),
    )
    op.create_table(
        "catalog_products",
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("product_type_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("kind='simple'", name="ck_catalog_product_simple"),
        sa.CheckConstraint("revision>0", name="ck_product_revision"),
        sa.ForeignKeyConstraint(
            ["product_type_id"], ["catalog_product_types.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_products_product_type_id"),
        "catalog_products",
        ["product_type_id"],
        unique=False,
    )
    op.create_table(
        "catalog_product_translations",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["catalog_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("product_id", "locale"),
    )
    op.create_table(
        "catalog_variants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("virtual", sa.Boolean(), nullable=False),
        sa.Column("downloadable", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "downloadable=false", name="ck_catalog_variant_files_unavailable"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["catalog_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id"),
    )
    op.create_table(
        "catalog_product_content_values",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=64), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "char_length(value)<=100000", name="ck_product_content_value_length"
        ),
        sa.ForeignKeyConstraint(
            ["block_id"], ["catalog_content_block_definitions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "locale"],
            [
                "catalog_product_translations.product_id",
                "catalog_product_translations.locale",
            ],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", "locale", "block_id"),
    )
    op.create_table(
        "catalog_variant_translations",
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["catalog_variants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("variant_id", "locale"),
    )
    op.create_table(
        "catalog_variant_content_values",
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=64), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "char_length(value)<=100000", name="ck_variant_content_value_length"
        ),
        sa.ForeignKeyConstraint(
            ["block_id"], ["catalog_content_block_definitions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["variant_id", "locale"],
            [
                "catalog_variant_translations.variant_id",
                "catalog_variant_translations.locale",
            ],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("variant_id", "locale", "block_id"),
    )
    # ### end Alembic commands ###
    system = UUID("00000000-0000-0000-0000-000000000000")
    now = datetime.now(UTC)
    type_id = UUID("c0000000-0000-4000-8000-000000000001")
    audit = {
        "revision": 1,
        "created_by": system,
        "updated_by": system,
        "created_at": now,
        "updated_at": now,
    }
    types = sa.table(
        "catalog_product_types",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("is_system", sa.Boolean()),
        sa.column("revision", sa.Integer()),
        sa.column("schema_version", sa.Integer()),
        sa.column("created_by", sa.UUID()),
        sa.column("updated_by", sa.UUID()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    blocks = sa.table(
        "catalog_content_block_definitions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("value_type", sa.String()),
        sa.column("is_system", sa.Boolean()),
        sa.column("revision", sa.Integer()),
        sa.column("created_by", sa.UUID()),
        sa.column("updated_by", sa.UUID()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    links = sa.table(
        "catalog_product_type_content_blocks",
        sa.column("product_type_id", sa.UUID()),
        sa.column("block_id", sa.UUID()),
        sa.column("scope", sa.String()),
        sa.column("required", sa.Boolean()),
        sa.column("position", sa.Integer()),
    )
    type_translations = sa.table(
        "catalog_product_type_translations",
        sa.column("product_type_id", sa.UUID()),
        sa.column("locale", sa.String()),
        sa.column("label", sa.String()),
    )
    block_translations = sa.table(
        "catalog_content_block_translations",
        sa.column("content_block_id", sa.UUID()),
        sa.column("locale", sa.String()),
        sa.column("label", sa.String()),
    )
    op.bulk_insert(
        types,
        [
            {
                "id": type_id,
                "code": "default",
                "is_system": True,
                "schema_version": 1,
                **audit,
            }
        ],
    )
    op.bulk_insert(
        type_translations,
        [
            {"product_type_id": type_id, "locale": locale, "label": label}
            for locale, label in [("en", "Default"), ("ru", "Чистый"), ("uk", "Чистий")]
        ],
    )
    for position, (code, value_type, label) in enumerate(
        [
            ("title", "text", "Название"),
            ("description", "rich_text", "Описание"),
            ("short_description", "rich_text", "Краткое описание"),
        ]
    ):
        identifier = UUID(f"c0000000-0000-4000-8000-{position+2:012d}")
        op.bulk_insert(
            blocks,
            [
                {
                    "id": identifier,
                    "code": code,
                    "value_type": value_type,
                    "is_system": True,
                    **audit,
                }
            ],
        )
        op.bulk_insert(
            block_translations,
            [
                {"content_block_id": identifier, "locale": locale, "label": value}
                for locale, value in [
                    ("ru", label),
                    ("en", code.replace("_", " ").title()),
                ]
            ],
        )
        op.bulk_insert(
            links,
            [
                {
                    "product_type_id": type_id,
                    "block_id": identifier,
                    "scope": scope,
                    "required": code == "title" and scope == "PRODUCT",
                    "position": position,
                }
                for scope in ("PRODUCT", "VARIANT")
                if scope == "PRODUCT" or code != "short_description"
            ],
        )


def downgrade() -> None:
    """Удаляет только Catalog в порядке внутренних зависимостей."""
    op.drop_table("catalog_variant_content_values")
    op.drop_table("catalog_variant_translations")
    op.drop_table("catalog_product_content_values")
    op.drop_table("catalog_variants")
    op.drop_table("catalog_product_translations")
    op.drop_table("catalog_products")
    op.drop_table("catalog_product_type_translations")
    op.drop_table("catalog_product_type_content_blocks")
    op.drop_table("catalog_content_block_translations")
    op.drop_table("catalog_product_types")
    op.drop_table("catalog_content_block_definitions")
