global:
  environment: prod

api:
  replicas: 2

worker:
  replicas: 2

cabinet:
  replicas: 2

ingress:
  host: control.example.com

certManager:
  issuerKind: ClusterIssuer
  issuerName: letsencrypt-production

dns:
  platformZone: example.com
