[project]
name = "dnk-runtime-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "commitizen>=4.13.9",
    "fastapi[standard]>=0.135.1",
    "pydantic>=2.12.5",
    "redis>=6.4.0",
    "sqlalchemy[asyncio]>=2.0.48",
    "uuid6>=2025.0.1",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
]
[project.scripts]
dnk-manage = "management.cli:main"

[tool.uv]
package = true
