apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dnk.runtime.fullname" . }}-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  labels:
    {{- include "dnk.runtime.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        location / { try_files $uri $uri/ /index.html; }
    }
