{{- if .Values.ingress.enabled }}
{{- $fullname := include "dnk.runtime.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "dnk.runtime.labels" . | nindent 4 }}
  annotations:
    {{- include "dnk.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - secretName: {{ include "dnk.ingress.tlsSecretName" . | quote }}
      hosts:
        - {{ include "dnk.runtime.hostname" . | quote }}
  rules:
    - host: {{ include "dnk.runtime.hostname" . | quote }}
      http:
        paths:
          {{- range $path := list "/api" }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-backend
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
