import src.modules.identity.infrastructure.persistence.user  # noqa: F401
import src.modules.identity.infrastructure.persistence.user_email  # noqa: F401
import src.modules.identity.infrastructure.persistence.access  # noqa: F401
import src.modules.tenancy.infrastructure.persistence.tenant  # noqa: F401
import src.modules.tenancy.infrastructure.persistence.tenant_domain  # noqa: F401
import src.modules.inventory.infrastructure.persistence  # noqa: F401
import src.modules.shared.infrastructure.events.integration_inbox_event_model  # noqa: F401
import src.modules.shared.infrastructure.events.integration_outbox_event_model  # noqa: F401
import src.modules.shared.infrastructure.jobs.scheduled_job_model  # noqa: F401
import src.modules.control_plane.infrastructure.models  # noqa: F401
