from typing import Protocol
from src.modules.channels.domain.aggregate import Channel
from src.modules.channels.domain.value_object.identifier import ChannelIdVO


class ChannelRepositoryProtocol(Protocol):
    async def add(self, channel: Channel) -> None: ...
    async def get_for_update(self, channel_id: ChannelIdVO) -> Channel | None: ...
    async def save(self, channel: Channel) -> None: ...
    async def delete(self, channel_id: ChannelIdVO) -> bool: ...
