application:
  server:
    publicOrigin: https://runtime.dniko.app
ingress:
  enabled: true
  className: nginx
  hosts:
  - '*.dniko.app'
  tls:
    clusterIssuer: letsencrypt-production
    secretName: runtime-dniko-wildcard-tls
