from src.modules.identity.presentation.depends.repositories import (
    UsersRepositoryDep,
    get_users_repository,
)
from src.modules.identity.presentation.depends.services import (
    UserServiceDep,
    get_user_service,
)
from src.modules.identity.presentation.depends.auth_repositories import (
    AuthUsersRepositoryDep,
    OtpChallengeStoreDep,
    SessionStoreDep,
    TenantContextReaderDep,
    get_auth_users_repository,
    get_otp_challenge_store,
    get_session_store,
    get_tenant_context_reader,
)
from src.modules.identity.presentation.depends.auth_services import (
    AuthSettingsDep,
    EmailSenderDep,
    InMemoryEmailSender,
    OtpServiceDep,
    SessionServiceDep,
    TokenManagerDep,
    get_auth_settings,
    get_email_sender,
    get_otp_service,
    get_session_service,
    get_token_manager,
)
from src.modules.identity.presentation.depends.auth_use_cases import (
    ConfirmEmailOtpUseCaseDep,
    LogoutCurrentSessionUseCaseDep,
    RequestEmailOtpUseCaseDep,
    get_confirm_email_otp_use_case,
    get_logout_current_session_use_case,
    get_request_email_otp_use_case,
)

__all__ = [
    "get_users_repository",
    "UsersRepositoryDep",
    "get_user_service",
    "UserServiceDep",
    "get_auth_users_repository",
    "AuthUsersRepositoryDep",
    "get_tenant_context_reader",
    "TenantContextReaderDep",
    "get_otp_challenge_store",
    "OtpChallengeStoreDep",
    "get_session_store",
    "SessionStoreDep",
    "get_auth_settings",
    "AuthSettingsDep",
    "get_token_manager",
    "TokenManagerDep",
    "get_email_sender",
    "EmailSenderDep",
    "get_otp_service",
    "OtpServiceDep",
    "get_session_service",
    "SessionServiceDep",
    "InMemoryEmailSender",
    "get_request_email_otp_use_case",
    "RequestEmailOtpUseCaseDep",
    "get_confirm_email_otp_use_case",
    "ConfirmEmailOtpUseCaseDep",
    "get_logout_current_session_use_case",
    "LogoutCurrentSessionUseCaseDep",
]
