from typing import Protocol

from src.modules.catalog.domain.category.aggregate import Category
from src.modules.catalog.domain.category.value_object.identifier import CategoryIdVO
from src.modules.catalog.domain.category.value_object.locale import CategoryLocaleVO
from src.modules.shared.domain.value_object.entity_id import EntityIdVO


class CategoryRepositoryProtocol(Protocol):
    async def lock_tree(self, tenant_id: EntityIdVO) -> None: ...
    async def add(self, category: Category) -> None: ...
    async def get_for_update(self, category_id: CategoryIdVO) -> Category | None: ...
    async def exists(self, category_id: CategoryIdVO) -> bool: ...
    async def is_descendant(
        self, candidate_id: CategoryIdVO, ancestor_id: CategoryIdVO
    ) -> bool: ...
    async def save_parent(self, category: Category) -> None: ...
    async def save_translation(
        self, category: Category, locale: CategoryLocaleVO
    ) -> None: ...
    async def has_children_or_products(self, category_id: CategoryIdVO) -> bool: ...
    async def delete(self, category_id: CategoryIdVO) -> None: ...
