{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dnk.core.fullname" . }}
  labels:
    {{- include "dnk.core.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName | quote }}
      hosts:
        - {{ include "dnk.core.hostname" . | quote }}
  rules:
    - host: {{ include "dnk.core.hostname" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dnk.core.fullname" . }}-gateway
                port:
                  number: {{ .Values.gateway.service.port }}
{{- end }}
