apiVersion: v2
name: dnk-control-plane
description: Django Control Plane, Nuxt, gateway and optional PostgreSQL/Redis
type: application
version: 0.3.0
appVersion: "0.0.1"
annotations:
  dnk.io/application-name: dnk-control-plane
kubeVersion: '>=1.25.0-0'
dependencies:
- name: postgresql
  version: 0.1.0
  condition: postgresql.enabled
- name: redis
  version: 0.1.0
  condition: redis.enabled
- name: dnk-common
  version: 0.3.0
  repository: file://../dnk-common
