from src.modules.schema_registry.domain.seed.field_seed import FieldSeed
from src.modules.schema_registry.domain.seed.index_seed import IndexSeed
from src.modules.schema_registry.domain.seed.object_seed import ObjectSeed
from src.modules.schema_registry.domain.seed.relation_seed import RelationSeed
from src.modules.schema_registry.domain.seed.schema_seed import SchemaSeed

SCHEMA_SEED = SchemaSeed(
    version=None,
    code="crm_diff_test",
    label="CRM Diff Test",
    objects=(
        ObjectSeed(
            singular_name="company",
            plural_name="companies",
            singular_label="Company",
            plural_label="Companies",
            description="Customer companies.",
            fields=(
                FieldSeed(
                    name="id",
                    type="uuid",
                    label="ID",
                    description="Company identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="name",
                    type="text",
                    label="Name",
                    description="Company name.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="website",
                    type="text",
                    label="Website",
                    description="Company website.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="is_active",
                    type="bool",
                    label="Is Active",
                    description="Company active flag.",
                    is_nullable=False,
                    default="true",
                ),
                FieldSeed(
                    name="created_at",
                    type="datetime",
                    label="Created At",
                    description="Creation timestamp.",
                    is_nullable=False,
                    default="CURRENT_TIMESTAMP",
                ),
            ),
            indexes=(
                IndexSeed(
                    name="companies_id_uq",
                    fields=("id",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="companies_name_idx",
                    fields=("name",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="companies_is_active_idx",
                    fields=("is_active",),
                    is_unique=False,
                ),
            ),
        ),
        ObjectSeed(
            singular_name="contact",
            plural_name="contacts",
            singular_label="Contact",
            plural_label="Contacts",
            description="Company contacts.",
            fields=(
                FieldSeed(
                    name="id",
                    type="uuid",
                    label="ID",
                    description="Contact identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="company_id",
                    type="uuid",
                    label="Company ID",
                    description="Owning company identifier.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="email",
                    type="text",
                    label="Email",
                    description="Primary email.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="first_name",
                    type="text",
                    label="First Name",
                    description="First name.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="last_name",
                    type="text",
                    label="Last Name",
                    description="Last name.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="phone",
                    type="text",
                    label="Phone",
                    description="Phone number.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="status",
                    type="select",
                    label="Status",
                    description="Lead/contact state.",
                    is_nullable=False,
                    default="'lead'",
                ),
                FieldSeed(
                    name="tags",
                    type="multiselect",
                    label="Tags",
                    description="Contact tags.",
                    is_nullable=True,
                    default="'[]'",
                ),
                FieldSeed(
                    name="created_at",
                    type="datetime",
                    label="Created At",
                    description="Creation timestamp.",
                    is_nullable=False,
                    default="CURRENT_TIMESTAMP",
                ),
            ),
            indexes=(
                IndexSeed(
                    name="contacts_id_uq",
                    fields=("id",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="contacts_company_id_idx",
                    fields=("company_id",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="contacts_email_uq",
                    fields=("email",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="contacts_status_idx",
                    fields=("status",),
                    is_unique=False,
                ),
            ),
            relations=(
                RelationSeed(
                    name="contacts_company_id_fk",
                    relation_type="many_to_one",
                    source_field="company_id",
                    target_object="company",
                    target_field="id",
                    on_delete="restrict",
                ),
            ),
        ),
        ObjectSeed(
            singular_name="deal",
            plural_name="deals",
            singular_label="Deal",
            plural_label="Deals",
            description="Sales deals.",
            fields=(
                FieldSeed(
                    name="id",
                    type="uuid",
                    label="ID",
                    description="Deal identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="company_id",
                    type="uuid",
                    label="Company ID",
                    description="Owning company identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="primary_contact_id",
                    type="uuid",
                    label="Primary Contact",
                    description="Main contact for this deal.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="title",
                    type="text",
                    label="Title",
                    description="Deal title.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="amount",
                    type="decimal",
                    label="Amount",
                    description="Planned amount.",
                    is_nullable=False,
                    default="0",
                ),
                FieldSeed(
                    name="priority",
                    type="int",
                    label="Priority",
                    description="Priority level.",
                    is_nullable=False,
                    default="0",
                ),
                FieldSeed(
                    name="stage",
                    type="select",
                    label="Stage",
                    description="Pipeline stage.",
                    is_nullable=False,
                    default="'new'",
                ),
                FieldSeed(
                    name="is_closed",
                    type="bool",
                    label="Is Closed",
                    description="Closed flag.",
                    is_nullable=False,
                    default="false",
                ),
                FieldSeed(
                    name="opened_on",
                    type="date",
                    label="Opened On",
                    description="Open date.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="meta",
                    type="json",
                    label="Meta",
                    description="Structured metadata.",
                    is_nullable=False,
                    default="'{}'",
                ),
                FieldSeed(
                    name="created_at",
                    type="datetime",
                    label="Created At",
                    description="Creation timestamp.",
                    is_nullable=False,
                    default="CURRENT_TIMESTAMP",
                ),
            ),
            indexes=(
                IndexSeed(
                    name="deals_id_uq",
                    fields=("id",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="deals_company_id_idx",
                    fields=("company_id",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="deals_primary_contact_id_idx",
                    fields=("primary_contact_id",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="deals_stage_idx",
                    fields=("stage",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="deals_is_closed_idx",
                    fields=("is_closed",),
                    is_unique=False,
                ),
            ),
            relations=(
                RelationSeed(
                    name="deals_company_id_fk",
                    relation_type="many_to_one",
                    source_field="company_id",
                    target_object="company",
                    target_field="id",
                    on_delete="restrict",
                ),
                RelationSeed(
                    name="deals_primary_contact_id_fk",
                    relation_type="one_to_one",
                    source_field="primary_contact_id",
                    target_object="contact",
                    target_field="id",
                    on_delete="restrict",
                ),
            ),
        ),
    ),
)
