from src.modules.schema_registry.domain.seed.field_seed import FieldSeed
from src.modules.schema_registry.domain.seed.index_seed import IndexSeed
from src.modules.schema_registry.domain.seed.object_seed import ObjectSeed
from src.modules.schema_registry.domain.seed.relation_seed import RelationSeed
from src.modules.schema_registry.domain.seed.schema_seed import SchemaSeed

SCHEMA_SEED = SchemaSeed(
    version=None,
    code="crm_diff_test_v2",
    label="CRM Diff V2",
    objects=(
        ObjectSeed(
            singular_name="company",
            plural_name="companies",
            singular_label="Company",
            plural_label="Companies",
            description="Customer companies v2.",
            fields=(
                FieldSeed(
                    name="id",
                    type="uuid",
                    label="ID",
                    description="Company identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="name",
                    type="text",
                    label="Name",
                    description="Company name.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="domain",
                    type="text",
                    label="Domain",
                    description="Primary company domain.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="is_active",
                    type="bool",
                    label="Is Active",
                    description="Company active flag.",
                    is_nullable=False,
                    default="true",
                ),
                FieldSeed(
                    name="created_at",
                    type="datetime",
                    label="Created At",
                    description="Creation timestamp.",
                    is_nullable=False,
                    default="CURRENT_TIMESTAMP",
                ),
            ),
            indexes=(
                IndexSeed(
                    name="companies_id_uq",
                    fields=("id",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="companies_name_idx",
                    fields=("name",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="companies_domain_idx",
                    fields=("domain",),
                    is_unique=False,
                ),
            ),
        ),
        ObjectSeed(
            singular_name="contact",
            plural_name="contacts",
            singular_label="Contact",
            plural_label="Contacts",
            description="Company contacts v2.",
            fields=(
                FieldSeed(
                    name="id",
                    type="uuid",
                    label="ID",
                    description="Contact identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="company_id",
                    type="uuid",
                    label="Company ID",
                    description="Owning company identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="email",
                    type="text",
                    label="Email",
                    description="Primary email.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="first_name",
                    type="text",
                    label="First Name",
                    description="First name.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="last_name",
                    type="text",
                    label="Last Name",
                    description="Last name.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="phone_number",
                    type="text",
                    label="Phone Number",
                    description="Primary phone number.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="mobile",
                    type="text",
                    label="Mobile",
                    description="Mobile phone.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="status",
                    type="select",
                    label="Status",
                    description="Lead/contact state.",
                    is_nullable=False,
                    default="'lead'",
                ),
                FieldSeed(
                    name="created_at",
                    type="datetime",
                    label="Created At",
                    description="Creation timestamp.",
                    is_nullable=False,
                    default="CURRENT_TIMESTAMP",
                ),
            ),
            indexes=(
                IndexSeed(
                    name="contacts_id_uq",
                    fields=("id",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="contacts_company_id_idx",
                    fields=("company_id",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="contacts_email_uq",
                    fields=("email",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="contacts_mobile_idx",
                    fields=("mobile",),
                    is_unique=False,
                ),
            ),
            relations=(
                RelationSeed(
                    name="contacts_company_fk",
                    relation_type="many_to_one",
                    source_field="company_id",
                    target_object="company",
                    target_field="id",
                    on_delete="restrict",
                ),
            ),
        ),
        ObjectSeed(
            singular_name="opportunity",
            plural_name="opportunities",
            singular_label="Opportunity",
            plural_label="Opportunities",
            description="Sales opportunities v2.",
            fields=(
                FieldSeed(
                    name="id",
                    type="uuid",
                    label="ID",
                    description="Opportunity identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="company_id",
                    type="uuid",
                    label="Company ID",
                    description="Owning company identifier.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="contact_id",
                    type="uuid",
                    label="Contact ID",
                    description="Related contact identifier.",
                    is_nullable=True,
                ),
                FieldSeed(
                    name="title",
                    type="text",
                    label="Title",
                    description="Opportunity title.",
                    is_nullable=False,
                ),
                FieldSeed(
                    name="amount",
                    type="decimal",
                    label="Amount",
                    description="Planned amount.",
                    is_nullable=False,
                    default="0",
                ),
                FieldSeed(
                    name="stage",
                    type="select",
                    label="Stage",
                    description="Pipeline stage.",
                    is_nullable=False,
                    default="'new'",
                ),
                FieldSeed(
                    name="is_closed",
                    type="bool",
                    label="Is Closed",
                    description="Closed flag.",
                    is_nullable=False,
                    default="false",
                ),
                FieldSeed(
                    name="created_at",
                    type="datetime",
                    label="Created At",
                    description="Creation timestamp.",
                    is_nullable=False,
                    default="CURRENT_TIMESTAMP",
                ),
            ),
            indexes=(
                IndexSeed(
                    name="opportunities_id_uq",
                    fields=("id",),
                    is_unique=True,
                ),
                IndexSeed(
                    name="opportunities_company_id_idx",
                    fields=("company_id",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="opportunities_contact_id_idx",
                    fields=("contact_id",),
                    is_unique=False,
                ),
                IndexSeed(
                    name="opportunities_stage_idx",
                    fields=("stage",),
                    is_unique=False,
                ),
            ),
            relations=(
                RelationSeed(
                    name="opportunities_company_id_fk",
                    relation_type="many_to_one",
                    source_field="company_id",
                    target_object="company",
                    target_field="id",
                    on_delete="restrict",
                ),
                RelationSeed(
                    name="opportunities_contact_id_fk",
                    relation_type="many_to_one",
                    source_field="contact_id",
                    target_object="contact",
                    target_field="id",
                    on_delete="restrict",
                ),
            ),
        ),
    ),
)
