{{- if .Values.enabled -}}
{{- include "dnk.postgresql.validate" . -}}
{{- if .Values.auth.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dnk.postgresql.fullname" . }}-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  labels:
    {{- include "dnk.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.auth.password.value | b64enc | quote }}
{{- end }}
{{- end }}
