from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.modules.tenancy.domain.entities import Tenant, TenantDataSource, TenantDomain


class TenantRepositoryProtocol(Protocol):
    async def add(self, tenant: Tenant) -> None: ...
    async def get_by_id(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_name(self, name: str) -> Tenant | None: ...
    async def exists_by_external_id(self, external_id: str) -> bool: ...
    async def exists_by_name(self, name: str) -> bool: ...


class TenantDomainRepositoryProtocol(Protocol):
    async def add(self, domain: TenantDomain) -> None: ...
    async def get_by_id(self, domain_id: UUID) -> TenantDomain | None: ...
    async def get_by_host(self, host: str) -> TenantDomain | None: ...
    async def get_api_host_by_tenant_id(self, tenant_id: UUID) -> str | None: ...
    async def exists_by_host(self, host: str) -> bool: ...


class TenantDataSourceRepositoryProtocol(Protocol):
    async def add(self, data_source: TenantDataSource) -> None: ...
    async def get_by_tenant_id(self, tenant_id: UUID) -> TenantDataSource | None: ...
    async def exists_by_schema(self, schema: str) -> bool: ...
