from typing import Protocol

from src.modules.shared.tokens.models import StoredToken


class TokenBackendProtocol(Protocol):
    async def set(self, key: str, value: StoredToken) -> None: ...
    async def get(self, key: str) -> StoredToken | None: ...
    async def delete(self, key: str) -> None: ...
