from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.domain.tenancy.entities import Tenant, TenantDomain
from src.domain.users.entities import User


class TenantRepositoryProtocol(Protocol):
    async def add(self, tenant: Tenant) -> None: ...
    async def get_by_id(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_name(self, name: str) -> Tenant | None: ...
    async def exists_by_name(self, name: str) -> bool: ...


class UserRepositoryProtocol(Protocol):
    async def add(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def exists_by_tenant_and_email(
        self,
        tenant_id: UUID,
        email: str,
    ) -> bool: ...


class TenantDomainRepositoryProtocol(Protocol):
    async def add(self, domain: TenantDomain) -> None: ...
    async def get_by_id(self, domain_id: UUID) -> TenantDomain | None: ...
    async def get_by_host(self, host: str) -> TenantDomain | None: ...
    async def exists_by_host(self, host: str) -> bool: ...
