# Generated by Django 6.0.8 on 2026-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add an optional patronymic without rewriting any existing identity data."""

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Отчество"
            ),
        ),
    ]
