CORE_SECRET_KEY: application.security.secretKey
CORE_MFA_ENCRYPTION_KEY: application.mfa.encryptionKey
CORE_EMAIL_HOST_PASSWORD: application.email.password
CORE_GOOGLE_CLIENT_SECRET: application.providers.google.clientSecret
CORE_GITHUB_CLIENT_SECRET: application.providers.github.clientSecret
CORE_TELEGRAM_LOGIN_CLIENT_SECRET: application.providers.telegramLogin.clientSecret
CORE_TELEGRAM_GATEWAY_TOKEN: application.providers.telegramGateway.token
