from src.modules.runtime_schema.domain.entities import (
    FieldMetadata,
    ObjectMetadata,
    RelationMetadata,
    SystemFieldDefinition,
    SystemObjectDefinition,
)
from src.modules.runtime_schema.domain.errors import (
    CrossTenantRelationError,
    FieldMetadataNotFoundError,
    FieldMetadataObjectMismatchError,
    FieldMetadataNameImmutableError,
    InvalidRelationFieldTypeError,
    InvalidRequiredRelationOnDeleteError,
    ObjectMetadataNotFoundError,
    ObjectMetadataNameImmutableError,
    RelationFieldAlreadyBoundError,
    RelationJunctionTableRequiredError,
    RelationJunctionTableAlreadyExistsError,
    RelationMetadataNotFoundError,
    RelationOwnerFieldRequiredError,
    RelationTargetFieldRequiredError,
    SystemRelationDefinitionError,
)

__all__ = [
    "ObjectMetadata",
    "FieldMetadata",
    "RelationMetadata",
    "SystemObjectDefinition",
    "SystemFieldDefinition",
    "ObjectMetadataNotFoundError",
    "ObjectMetadataNameImmutableError",
    "FieldMetadataNotFoundError",
    "FieldMetadataObjectMismatchError",
    "FieldMetadataNameImmutableError",
    "RelationMetadataNotFoundError",
    "RelationFieldAlreadyBoundError",
    "RelationOwnerFieldRequiredError",
    "RelationTargetFieldRequiredError",
    "RelationJunctionTableAlreadyExistsError",
    "RelationJunctionTableRequiredError",
    "InvalidRelationFieldTypeError",
    "InvalidRequiredRelationOnDeleteError",
    "CrossTenantRelationError",
    "SystemRelationDefinitionError",
]
